apiVersion: v1
kind: Service
metadata:
  name: db-postgres
spec:
  selector:
    app: db-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-postgres-deploy
spec:
  serviceName: db-postgres
  selector:
    matchLabels:
      app: db-postgres
  template:
      metadata:
        labels:
          app: db-postgres
      spec:
        containers:
          - name: db-postgres
            image: postgres:13.1-alpine
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_USER
                value: compose-postgres
              - name: POSTGRES_PASSWORD
                value: compose-postgres
            volumeMounts:
              - name: user-data
                mountPath: /var/lib/postgresql/data
        volumes:
          - name: user-data
            hostPath:
              path: /var/data
