apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app-red
  template:
    metadata:
      labels:
        app: spring-app-red
    spec:
      containers:
        - name: spring-app
          image: gaurangipradhan/ecom
          ports:
            - containerPort: 8900
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-postgres:5432/compose-postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: compose-postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: compose-postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create

